export default [
  {
    name: 'One Card',
    slug: 'single',
    useMinor: true,
    useInverted: true,
    width: 24,
    height: 42,
    positions: [{ x: 0, y: 0 }],
    add: { x: 0, y: 0 },
  },
  {
    name: 'Triad',
    slug: 'triad',
    useMinor: true,
    useInverted: true,
    width: 52,
    height: 56,
    positions: [
      { name: 'Present', x: 0, y: -14 },
      { name: 'Past', x: -18, y: -14 },
      { name: 'Future', x: 18, y: -14 },
    ],
    add: { x: 0, y: 14 },
  },
  {
    name: 'Celtic Cross',
    slug: 'celtic-cross',
    useMinor: true,
    useInverted: true,
    width: 82,
    height: 112,
    positions: [
      { name: 'Covering', x: -11, y: 14 },
      { name: 'Crossing', x: -11, y: 14, tilt: -90 },
      { name: 'Past', x: -33, y: 14 },
      { name: 'Future', x: 11, y: 14 },
      { name: 'Subconscious', x: -11, y: 42 },
      { name: 'Aspirations', x: -11, y: -14 },
      { name: 'Advice', x: 31, y: 42 },
      { name: 'Environment', x: 31, y: 14 },
      { name: 'Hopes/Fears', x: 31, y: -14 },
      { name: 'Outcome', x: 33, y: -42 },
    ],
    add: { x: -33, y: -42 },
  },
  {
    name: 'Tree of Life',
    slug: 'tree-of-life',
    useMinor: false,
    useInverted: false,
    width: 52,
    height: 140,
    positions: [
      { name: 'Keter', x: 0, y: -56 },
      { name: 'Chochmah', x: 18, y: -42 },
      { name: 'Binah', x: -18, y: -42 },
      { name: 'Chesed', x: 18, y: -14 },
      { name: 'Gevurah', x: -18, y: -14 },
      { name: 'Tiferet', x: 0, y: 0 },
      { name: 'Netzach', x: 18, y: 14 },
      { name: 'Hod', x: -18, y: 14 },
      { name: 'Yesod', x: 0, y: 28 },
      { name: 'Malchut', x: 0, y: 56 },
    ],
    add: { x: 0, y: -28 },
  },
  {
    name: 'Tetraktys',
    slug: 'tetraktys',
    useMinor: true,
    useInverted: true,
    width: 70,
    height: 112,
    positions: [
      { name: 'Fire', x: 27, y: 42 },
      { name: 'Air', x: 9, y: 42 },
      { name: 'Water', x: -9, y: 42 },
      { name: 'Earth', x: -27, y: 42 },
      { name: 'Creator', x: 18, y: 14 },
      { name: 'Sustainer', x: 0, y: 14 },
      { name: 'Destroyer', x: -18, y: 14 },
      { name: 'Light', x: 9, y: -14 },
      { name: 'Dark', x: -9, y: -14 },
      { name: 'Summit', x: 0, y: -42 },
    ],
    add: { x: -27, y: -42 },
  },
  {
    name: '15-Card X',
    slug: 'x15',
    useMinor: true,
    useInverted: true,
    width: 118,
    height: 84,
    positions: [
      { x: 0, y: 0 },
      { x: -17, y: 0 },
      { x: 17, y: 0 },
      { x: -51, y: -28 },
      { x: -34, y: -28 },
      { x: -17, y: -28 },
      { x: 17, y: 28 },
      { x: 34, y: 28 },
      { x: 51, y: 28 },
      { x: -51, y: 28 },
      { x: -34, y: 28 },
      { x: -17, y: 28 },
      { x: 17, y: -28 },
      { x: 34, y: -28 },
      { x: 51, y: -28 },
    ],
    add: { x: -42, y: 0 },
  },
];
